#Main site name
site_name: Starter Template

#Documentation content management goes here
nav:
  - Congratulations!:  contents/main/pages/index.md

# Navigation reference of 'System Documentation methods'.

#  - What to know?:  contents/main/pages/what_to_know.md
#  - Directories and files:  contents/main/pages/directories_and_files.md
#  - Working on the contents:
#      - Approach and practices: contents/working_on_the_contents/pages/approach_and_practices.md
#      - Documentation structure: contents/working_on_the_contents/pages/documentation_structure.md
#  - Sample Documentations:
#      - Notification:
#          - System Overview: contents/sample_documentations/notification/pages/notification.md
#          - Database:
#              - Overview: contents/sample_documentations/notification/pages/database/overview.md
#              - Schema:
#                  - Schema 1: contents/sample_documentations/notification/pages/database/schema/schema_1.md
#                  - Schema 2: contents/sample_documentations/notification/pages/database/schema/schema_2.md
#                  - Schema 3: contents/sample_documentations/notification/pages/database/schema/schema_3.md
#              - Users:
#                  - dob: contents/sample_documentations/_sample_database/pages/users/dbo.md
#                  - sys: contents/sample_documentations/_sample_database/pages/users/sys.md
#                  - admin: contents/sample_documentations/_sample_database/pages/users/admin.md
#                  - guest: contents/sample_documentations/_sample_database/pages/users/guest.md
#                  - user 2: contents/sample_documentations/_sample_database/pages/users/user_2.md


#Configurations
theme:
  name: material
  logo: brand.png
  favicon: brand.png
  custom_dir: docs/overrides
  palette:
    scheme: slate
    primary: indigo
    accent: orange

#Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.superfences
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
#      clickable_checkbox: true