#Main site name
site_name: System Documentation methods

#Documentation content management goes here
nav:
  - Welcome:  contents/main/pages/index.md
  - What to know?:  contents/main/pages/what_to_know.md
  - Directories and files:  contents/main/pages/directories_and_files.md
  - Working on the contents:
      - Approach and practices: contents/working_on_the_contents/pages/approach_and_practices.md
      - Documentation structure: contents/working_on_the_contents/pages/documentation_structure.md
  - Sample Documentations:
      - Notification:
          - System Overview: contents/sample_documentations/notification/pages/notification.md
          - Database:
              - Overview: contents/sample_documentations/notification/pages/database/overview.md
              - Schema:
                  - Schema 1: contents/sample_documentations/notification/pages/database/schema/schema_1.md
                  - Schema 2: contents/sample_documentations/notification/pages/database/schema/schema_2.md
                  - Schema 3: contents/sample_documentations/notification/pages/database/schema/schema_3.md
              - Users:
                  - dob: contents/sample_documentations/_sample_database/pages/users/dbo.md
                  - sys: contents/sample_documentations/_sample_database/pages/users/sys.md
                  - admin: contents/sample_documentations/_sample_database/pages/users/admin.md
                  - guest: contents/sample_documentations/_sample_database/pages/users/guest.md
                  - user 2: contents/sample_documentations/_sample_database/pages/users/user_2.md
  - Projects Documentations:
      - Digital Profile:
          - System Overview: contents//projects/digital_profile/architechture_overview/pages/introduction.md
          - Setup: contents/projects/digital_profile/getting_started/pages/setup.md
          - Get Started: contents/projects/digital_profile/getting_started/pages/starting.md
          - Usage: contents/projects/digital_profile/getting_started/pages/usage.md
          - Dashboard:
              - Forms:
                  - Tips: contents/projects/digital_profile/main/forms/pages/form_creation_tips.md
                  - List: contents/projects/digital_profile/main/forms/pages/all_forms.md
              - Users:
                  - Permission:
                      - koboform:
                          - Sharing Form: contents/projects/digital_profile/main/users/pages/koboform_api.md
                  - information:
                      - User Detail: contents/projects/digital_profile/main/users/pages/user_detail.md
              - Reports:
                  - Report Page: contents/projects/digital_profile/main/reporting/pages/report_page.md
                  - Report Data: contents/projects/digital_profile/main/reporting/pages/data_analysis.md
                  - Report List: contents/projects/digital_profile/main/reporting/pages/report_list.md
                  - Public Link: contents/projects/digital_profile/main/reporting/pages/public_link.md
                  - Report Detail: contents/projects/digital_profile/main/reporting/pages/report_detail.md
          - Issues: contents/projects/digital_profile/issues/pages/issues.md


#Configurations
theme:
  name: material
  logo: brand.png
  favicon: brand.png
  custom_dir: docs/overrides
  palette:
    scheme: slate
    primary: indigo
    accent: orange

#Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.superfences
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
#      clickable_checkbox: true